[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm run start"
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  
[build.environment]
  NODE_VERSION = "18"