[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm run start"
  
[[redirects]]
  from = "/updates/*"
  to = "/updates/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/about"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "https://luthienresearch.github.io/luthien-pbc-site/"
  status = 301
  force = true
  
[build.environment]
  NODE_VERSION = "18"
